# Generated by Django 4.0.3 on 2022-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='mouvement_litteraire',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='choisir', max_length=6),
        ),
    ]
