# Generated by Django 4.0.3 on 2022-04-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_remove_livre_mouvement_litteraire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mouvement',
            new_name='Mouv',
        ),
    ]
