# Generated by Django 4.0.3 on 2022-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_rename_mouvement_mouv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement_litteraire', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Mouv',
        ),
    ]
