# Generated by Django 4.0.3 on 2022-04-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0007_mouvement_delete_mouv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvement',
            old_name='mouvement_litteraire',
            new_name='nom',
        ),
    ]
