# Generated by Django 4.0.3 on 2022-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_rename_nom_mouvement_mouvement_litteraire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mouvement',
        ),
        migrations.AddField(
            model_name='livre',
            name='mouvement_litteraire',
            field=models.CharField(blank=True, choices=[('', 'Nouveau Roman'), ('', 'Surréalisme'), ('', 'Symbolisme'), ('', 'Naturalisme'), ('', 'Réalisme'), ('', 'Romantisme'), ('', 'Lumières'), ('', 'Classicisme'), ('', 'Humanisme'), ('', 'Baroque'), ('', 'Autre')], max_length=6),
        ),
    ]
