# Generated by Django 4.0.3 on 2022-04-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_delete_mouvement_livre_mouvement_litteraire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livre',
            old_name='mouvement_litteraire',
            new_name='mouvement',
        ),
    ]
