# Generated by Django 4.0.3 on 2022-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0011_rename_mouvement_litteraire_livre_mouvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouvement_litteraire', models.CharField(max_length=100)),
            ],
        ),
    ]
