# Generated by Django 4.0.3 on 2022-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0012_mouvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('nombre_places', models.DateField(blank=True, null=True)),
                ('date_production', models.IntegerField()),
                ('puissance', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.DeleteModel(
            name='Mouvement',
        ),
    ]
