# Generated by Django 4.0.4 on 2022-04-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0015_marque_rename_nombre_places_voiture_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marque',
            old_name='name',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='modele',
            old_name='name',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='voiture',
            old_name='name',
            new_name='Nom',
        ),
    ]
