# Generated by Django 4.0.4 on 2022-04-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0016_rename_name_marque_nom_rename_name_modele_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marque',
            old_name='Nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='modele',
            old_name='Nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voiture',
            old_name='Nom',
            new_name='name',
        ),
    ]
