# Generated by Django 4.0.4 on 2022-04-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0017_rename_nom_marque_name_rename_nom_modele_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='date_production',
            new_name='date_de_commande',
        ),
    ]
