# Generated by Django 4.0.4 on 2022-04-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0019_ajout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ajout',
        ),
    ]
