# Generated by Django 4.0.4 on 2022-04-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0020_delete_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjoutMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=30)),
                ('modele', models.CharField(max_length=30)),
            ],
        ),
    ]
