# Generated by Django 4.0.4 on 2022-04-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0021_ajoutmm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajoutmm',
            old_name='modele',
            new_name='name',
        ),
    ]
