# Generated by Django 4.0.4 on 2022-04-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0022_rename_modele_ajoutmm_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AjoutMM',
        ),
    ]
